# Generated by Django 5.2.11 on 2026-05-01 21:47

import ndarraydjango.fields
import numpy
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_encodings', ndarraydjango.fields.NDArrayField(dtype=numpy.float64, editable=True, shape=(128,))),
            ],
        ),
    ]
