# Generated by Django 5.2.11 on 2026-05-04 16:21

import django.db.models.deletion
import ndarraydjango.fields
import numpy
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', ndarraydjango.fields.NDArrayField(dtype=numpy.float64, editable=True, shape=(128,))),
                ('image', models.ImageField(upload_to='face_templates/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('USER_CREATED_OK', 'User created OK'), ('USER_CREATED_FAIL', 'User created FAIL'), ('LOGIN_PWD_OK', 'Login password OK'), ('LOGIN_PWD_FAIL', 'Login password FAIL'), ('OTP_OK', 'OTP OK'), ('OTP_FAIL', 'OTP FAIL'), ('FACE_OK', 'Face OK'), ('FACE_FAIL', 'Face FAIL')], max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TOTPSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=128, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TestUser',
        ),
    ]
